//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimRegisPortal.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimRegisPortal.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер не зміг виконати ваш запит. Будь ласка, спробуйте пізніше. Якщо проблема не зникає, зверніться до служби підтримки. Подробиці помилки містяться в журналах сервера..
        /// </summary>
        public static string Exception_Others {
            get {
                return ResourceManager.GetString("Exception.Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас немає дозволу на доступ до {0}..
        /// </summary>
        public static string Exception_Resource_Forbidden {
            get {
                return ResourceManager.GetString("Exception.Resource.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запитаний об&apos;єкт {0} не знайдено..
        /// </summary>
        public static string Exception_Resource_NotFound {
            get {
                return ResourceManager.GetString("Exception.Resource.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сесія закінчилась. Будь ласка, увійдіть знову..
        /// </summary>
        public static string Exception_UserSession_Expired {
            get {
                return ResourceManager.GetString("Exception.UserSession.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сесію не знайдено. Будь ласка, увійдіть знову..
        /// </summary>
        public static string Exception_UserSession_NotFound {
            get {
                return ResourceManager.GetString("Exception.UserSession.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контракт з таким номером вже існує..
        /// </summary>
        public static string Validation_Contract_Number_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.Contract.Number.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для цього працівника вже існує перекривний контракт у вибраному проєкті..
        /// </summary>
        public static string Validation_Contract_Range_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.Contract.Range.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обліковий запис з цією електронною адресою вже існує..
        /// </summary>
        public static string Validation_Email_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.Email.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильна електронна адреса..
        /// </summary>
        public static string Validation_Email_Invalid {
            get {
                return ResourceManager.GetString("Validation.Email.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата звільнення має бути порожньою або пізнішою за дату найму..
        /// </summary>
        public static string Validation_Employee_DismissalDate {
            get {
                return ResourceManager.GetString("Validation.Employee.DismissalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почасова ставка повинна бути додатним значенням..
        /// </summary>
        public static string Validation_Employee_HourlyRate {
            get {
                return ResourceManager.GetString("Validation.Employee.HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей обліковий запис вже пов&apos;язаний з іншим працівником..
        /// </summary>
        public static string Validation_Employee_User_AlreadyLinked {
            get {
                return ResourceManager.GetString("Validation.Employee.User.AlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість годин має бути більшою за нуль..
        /// </summary>
        public static string Validation_EmployeeActivity_NegativeDuration {
            get {
                return ResourceManager.GetString("Validation.EmployeeActivity.NegativeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей працівник не має контракту на вибраний проєкт і період..
        /// </summary>
        public static string Validation_EmployeeActivity_NotContracted {
            get {
                return ResourceManager.GetString("Validation.EmployeeActivity.NotContracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс обміну з такими значеннями &quot;З валюти&quot;, &quot;До валюти&quot; та Дата вже існує..
        /// </summary>
        public static string Validation_ExchangeRate_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.ExchangeRate.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс обміну має бути більшим за нуль..
        /// </summary>
        public static string Validation_ExchangeRate_Negative {
            get {
                return ResourceManager.GetString("Validation.ExchangeRate.Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс обміну не знайдено..
        /// </summary>
        public static string Validation_ExchangeRate_NotFound {
            get {
                return ResourceManager.GetString("Validation.ExchangeRate.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; є обов’язковим..
        /// </summary>
        public static string Validation_Field_Required {
            get {
                return ResourceManager.GetString("Validation.Field.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обліковий запис з таким логіном вже існує..
        /// </summary>
        public static string Validation_Login_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.Login.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обліковий запис з такою електронною адресою не знайдено..
        /// </summary>
        public static string Validation_Login_Email_NotFound {
            get {
                return ResourceManager.GetString("Validation.Login.Email.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний логін або пароль..
        /// </summary>
        public static string Validation_Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Validation.Login.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума фіксованих податків перевищує заробітну плату працівника..
        /// </summary>
        public static string Validation_NetSalary_Negative {
            get {
                return ResourceManager.GetString("Validation.NetSalary.Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль може містити лише літери та цифри..
        /// </summary>
        public static string Validation_Password_Invalid {
            get {
                return ResourceManager.GetString("Validation.Password.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слабкий пароль: має містити щонайменше 6 символів, включаючи великі, малі літери та цифру..
        /// </summary>
        public static string Validation_Password_Weak {
            get {
                return ResourceManager.GetString("Validation.Password.Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовий звіт вже затверджено. Зверніться до свого менеджера, щоб внести зміни..
        /// </summary>
        public static string Validation_TimeReport_Finilized {
            get {
                return ResourceManager.GetString("Validation.TimeReport.Finilized", resourceCulture);
            }
        }
    }
}
