//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimRegisPortal.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimRegisPortal.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server was unable to complete your request. Please try again later. If this problem persists, please contact support. Server logs contain details of this error..
        /// </summary>
        public static string Exception_Others {
            get {
                return ResourceManager.GetString("Exception.Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have permission to access the {0}..
        /// </summary>
        public static string Exception_Resource_Forbidden {
            get {
                return ResourceManager.GetString("Exception.Resource.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested {0} was not found..
        /// </summary>
        public static string Exception_Resource_NotFound {
            get {
                return ResourceManager.GetString("Exception.Resource.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has expired. Please sign in again..
        /// </summary>
        public static string Exception_UserSession_Expired {
            get {
                return ResourceManager.GetString("Exception.UserSession.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found. Please sign in again..
        /// </summary>
        public static string Exception_UserSession_NotFound {
            get {
                return ResourceManager.GetString("Exception.UserSession.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A contract with the same number already exists..
        /// </summary>
        public static string Validation_Contract_Number_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.Contract.Number.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An overlapping contract already exists for this employee in the selected project..
        /// </summary>
        public static string Validation_Contract_Range_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.Contract.Range.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email already exists..
        /// </summary>
        public static string Validation_Email_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.Email.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string Validation_Email_Invalid {
            get {
                return ResourceManager.GetString("Validation.Email.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissal date must be empty or later than hire date..
        /// </summary>
        public static string Validation_Employee_DismissalDate {
            get {
                return ResourceManager.GetString("Validation.Employee.DismissalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate must be a positive value..
        /// </summary>
        public static string Validation_Employee_HourlyRate {
            get {
                return ResourceManager.GetString("Validation.Employee.HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User account is already linked to another Employee..
        /// </summary>
        public static string Validation_Employee_User_AlreadyLinked {
            get {
                return ResourceManager.GetString("Validation.Employee.User.AlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours must be greater than zero..
        /// </summary>
        public static string Validation_EmployeeActivity_NegativeDuration {
            get {
                return ResourceManager.GetString("Validation.EmployeeActivity.NegativeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not contracted for selected project and period..
        /// </summary>
        public static string Validation_EmployeeActivity_NotContracted {
            get {
                return ResourceManager.GetString("Validation.EmployeeActivity.NotContracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exchange rate with this CurrencyFrom, CurrencyTo and Date already exists..
        /// </summary>
        public static string Validation_ExchangeRate_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.ExchangeRate.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate must be greater than zero..
        /// </summary>
        public static string Validation_ExchangeRate_Negative {
            get {
                return ResourceManager.GetString("Validation.ExchangeRate.Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate not found..
        /// </summary>
        public static string Validation_ExchangeRate_NotFound {
            get {
                return ResourceManager.GetString("Validation.ExchangeRate.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is required..
        /// </summary>
        public static string Validation_Field_Required {
            get {
                return ResourceManager.GetString("Validation.Field.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this login already exists..
        /// </summary>
        public static string Validation_Login_AlreadyExists {
            get {
                return ResourceManager.GetString("Validation.Login.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found with this email..
        /// </summary>
        public static string Validation_Login_Email_NotFound {
            get {
                return ResourceManager.GetString("Validation.Login.Email.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password..
        /// </summary>
        public static string Validation_Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Validation.Login.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of fixed taxes exceeds the employee&apos;s salary..
        /// </summary>
        public static string Validation_NetSalary_Negative {
            get {
                return ResourceManager.GetString("Validation.NetSalary.Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can only contain letters and digits..
        /// </summary>
        public static string Validation_Password_Invalid {
            get {
                return ResourceManager.GetString("Validation.Password.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password: must be at least 6 characters and include uppercase, lowercase, and a digit..
        /// </summary>
        public static string Validation_Password_Weak {
            get {
                return ResourceManager.GetString("Validation.Password.Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Report is already finilized. Please contact your manager to apply changes..
        /// </summary>
        public static string Validation_TimeReport_Finilized {
            get {
                return ResourceManager.GetString("Validation.TimeReport.Finilized", resourceCulture);
            }
        }
    }
}
